package dev.osujava.gameplay;

/** Named visual slots for the default gameplay skin and future texture-backed skins. */
public enum GameplaySkinComponent {
    BACKGROUND, PLAYFIELD_TINT,
    HITCIRCLE_BORDER, HITCIRCLE_OVERLAY, HITCIRCLE_MISS, APPROACHCIRCLE,
    SLIDER_BORDER, SLIDER_INNER, SLIDERBALL, REVERSEARROW,
    FOLLOWCIRCLE_FILL, FOLLOWCIRCLE_BORDER,
    SPINNER_FIELD, SPINNER_RING, SPINNER_PROGRESS, SPINNER_COMPLETE, SPINNER_MISS,
    HUD_TEXT, HUD_SECONDARY, HUD_PANEL, JUDGEMENT
}
